name: AndroidBuild

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          ./gradlew test || true

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

#  sonarqube-analysis:
#    needs: [unit-test]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.1.0
#
#      - name: Setup Java JDK
#        uses: actions/setup-java@v3.13.0
#        with:
#          java-version: '18'
#          distribution: 'adopt'
#
#      - name: SonarQube Analysis
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: [sonarqube-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build || true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCiCd.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    needs: [ build ]
    name: Distribute For Alpha Testing
    runs-on: ubuntu-latest
    steps:
      - name: Download latest artifact
        uses: actions/download-artifact@v2
        with:
          name: AndroidCiCd.apk

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: pulkit/AndroidCiCd
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: AlphaTesters
          file: AndroidCiCd.apk
          notifyTesters: true
          debug: true